---
prompt_file_stage_1: prompts/default.json
prompt_file_stage_2: prompts/classify_harm.json
prompt_file_dehumanizing: prompts/classify_dehumanizing.json
prompt_file_stigmatizing: prompts/classify_stigmatizing.json
prompt_file_stereotyping: prompts/classify_stereotyping.json
prompt_file_simplifying: prompts/classify_simplifying.json
prompt_file_othering: prompts/classify_othering.json
prompt_file_othering_identify_target: prompts/classify_othering_identify_target.json
prompt_file_othering_is_social_group: prompts/classify_othering_is_social_group.json
prompt_file_othering_portrayal: prompts/classify_othering_portrayal.json
prompt_file_othering_identify_unified_group: prompts/classify_othering_identify_unified_group.json
dataset: ../data/annotations_100.json
model: llama3.3-70b-q4:latest
seed: 42
temperature: 0.15
workers: 4
save_interval: 50
max_retries: 3