---
prompt_file_stage_1: prompts/default.json
prompt_file_stage_2: prompts/classify_harm.json
prompt_file_dehumanizing: prompts/classify_dehumanizing.json
prompt_file_stigmatizing: prompts/classify_stigmatizing.json
prompt_file_stereotyping: prompts/classify_stereotyping.json
prompt_file_simplifying: prompts/classify_simplifying.json
prompt_file_othering: prompts/classify_othering.json
dataset: ../data/annotations_100.json
model: llama3.3:70b-instruct-q4_0
seed: 42
temperature: 0.15
workers: 4
save_interval: 20
max_retries: 3